### ISSUE TITLE
Task: Rethink Participation Actions

### ISSUE THREAD

**Issue by zysim** [leaderboardsgg/leaderboard-backend#107]
Both create and update participation actions need rethinking. The logic in both are pretty weird, and might even be entirely wrong. A few things off the top of my head are:
* For updating participations:
    * We may want to allow updating other users' participations, and not just the caller's
    * A user can and will have multiple participations, while we only search for the first row in the DB on every search

### Affected Functionality

- Obviously, the mentioned actions

### Other Relevant Issues

\-

**Comment by TheTedder** [comment]
Participations not part of MVP. One user has many runs for now.
