### ISSUE TITLE
MVP: Variables

### ISSUE THREAD

**Issue by zysim** [leaderboardsgg/leaderboard-backend#114]
🔨🔨🔨

* Append each item with the PR that solves it.
* Deletions are _soft_ unless explicitly stated otherwise.

## Model/Relationships

- [ ] Create the model - refer to [MVP](https://github.com/leaderboardsgg/leaderboard-backend/wiki/MVP-Overview#variable)
  - One Variable to many [Variable Values](https://github.com/leaderboardsgg/leaderboard-backend/wiki/MVP-Overview#variable-value) via Variable ID
    - Cascades on delete
  - One Variable to many Category Variables via Variable ID
    - Cascades on delete

## Controller Actions

- [ ] GET Variable with ID
- [ ] GET Categories for Variable via Category Variables with Variable ID
- [ ] GET Run for Variable via Run Variables with Variable ID
- [ ] GET Variable Values for Variable with Variable ID
- [ ] POST Variable as admin with:
  - ID (long; pk);
  - Name (string);
  - Slug (string);
  - Condition: Name OR Slug **must not** already exist
- [ ] PUT Variable as admin
  - Condition: Name OR Slug **must not** already exist
- [ ] DELETE Variable as admin with ID

## Post-action Behaviours

\-

## Other Relevant Issues

\-

**Comment by TheTedder** [comment]
not MVP
