### ISSUE TITLE
Task: Login endpoint

### ISSUE THREAD

**Issue by Dalet** [leaderboardsgg/leaderboard-backend#149]
Parent issue: https://github.com/leaderboardsgg/leaderboard-backend/issues/144

`POST /login`

Request body fields:
- email: string
- password: string

Successful response body fields:
- token: string

- [x] If the client does not supply both an email and a password in the request body, the server must respond with a `422 UNPROCESSABLE CONTENT` status code.
- [x] If the client supplies an email address that does not correspond to an existing user account, the server must respond with a `404 NOT FOUND` status code.
- [x] If the client supplies an email adresss that does correspond to an existing user account but the password does not match said user's password, the server must respond with a `401 UNAUTHORIZED` status code.
- [x] If the client supplies an email address that corresponds to an existing user account and a correct password that matches the encrypted password for said user whose role is `BANNED`, the server must return a `403 FORBIDDEN` status code.
- [x] Upon a successful login, the server must return a `200 OK` status code as well as a JSON web token in the response body.

### Affected Functionality
Login on front-end will break because of the URI change

### Other Relevant Issues
- [Give user feedback during account creation/login](https://github.com/leaderboardsgg/leaderboard-site/issues/563)

**Comment by TheTedder** [comment]
Is this issue complete? If so, close it as completed.
