### ISSUE TITLE
Task: Confirm account endpoint

### ISSUE THREAD

**Issue by Dalet** [leaderboardsgg/leaderboard-backend#155]
Parent issue: https://github.com/leaderboardsgg/leaderboard-backend/issues/153

Endpoint: `PUT /account/confirm/{confirmationId}`

URL Parameters:
- `confirmationId`: GUID

### Requirements
- [ ] If the confirmation ID provided by the client is not a base64-encoded ID of an existing confirmation record in the database, the server must respond with a `404 NOT FOUND` status code.
- [ ] If the confirmation specified by the client has an `ExpiredAt` timestamp that is in the past, the server must respond with a `404 NOT FOUND` status code
- [ ] If the recovery specified by the client has a non-null `UsedAt` field, the server must respond with a `404 NOT FOUND` status code.
- [ ] If the user associated with the confirmation specified by the client has a role of `CONFIRMED` or `ADMINISTRATOR`, the server must respond with a `409 CONFLICT` status code, indicating that the user account has already been confirmed.
- [ ] If the account is successfully confirmed, the server must set the associated users's role to `CONFIRMED`, set the specified confirmation's `UsedAt` timestamp to the current time, and respond with a `200 OK` status code.

### Procedure
This is what happens when the user confirms their account via a link sent to their email inbox.

Inputs:
- confirmation ID: GUID

- [ ] The user associated with the confirmation identified by the supplied ID must have their `Role` field updated from `REGISTERED` to `CONFIRMED` in the database and the procedure must return `TRUE`.
- [ ] If the user's role was not `REGISTERED`. the user's role must not be altered.

**Comment by zysim** [comment]
>  409 CONFLICT status code, indicating that the user account has already been confirmed.
Could do a 204 instead?
