### ISSUE TITLE
[WIP] Task: Logout endpoint

### ISSUE THREAD

**Issue by Dalet** [leaderboardsgg/leaderboard-backend#160]
# ⚠️ This issue is a Work-In-Progress, it needs to be fleshed out

`POST /logout`
Requires authentication

- [ ] If the client does not provide a valid session token, the server must respond with a `401 UNAUTHORIZED` status code.
- [ ] If the client provides a valid session token, the user session must be terminated and the server must respond with a `200 OK` status code.

**Comment by TheTedder** [comment]
What's the status on this? Currently, logging out seems to work fine without it. Is this still needed?

**Comment by zysim** [comment]
Yeah I think it's done, already. We do save a session token in user state, and clear it on logout.
