### ISSUE TITLE
Task: Remove Seed Data

### ISSUE THREAD

**Issue by TheTedder** [leaderboardsgg/leaderboard-backend#166]
Currently, the DB is seeded with a single user record for an admin user. This is undesireable because the repo is public so anyone could log into this admin account and wreak havoc on the website. My suggestion is to remove this seed data or make sure it only gets added to the DB in local test environments and not any sort of production environment or non-local testing or development environment. This could be controlled with environment variables.

**Comment by Dalet** [comment]
It's currently already customizable with environment variables but it was stupid of me to put it in a migration.
that's why you don't code late at night kids
