### ISSUE TITLE
Task: Use Email Service with Queue/Transactional Outbox

### ISSUE THREAD

**Issue by zysim** [leaderboardsgg/leaderboard-backend#208]
Our current email service can get flaky, and cause emails to not be sent. This should be sorted by swapping to what's stated in the title.

### Affected Functionality

Emails will be impacted.

### Other Relevant Issues

N/A

**Comment by TheTedder** [comment]
We should move this up in priority. It's getting really hard to test the app when emails don't send half the time. I'm taking it out of the backlog and putting it in the frontlog.
