### ISSUE TITLE
Add Role field to UserViewModel

### ISSUE THREAD

**Issue by TheTedder** [leaderboardsgg/leaderboard-backend#210]
The frontend needs to know a user's role for various purposes, so we should add it to UserViewModel and include it in responses from endpoints that return UserViewModels.
### Affected Functionality
none

### Other Relevant Issues
[frontend #591](https://github.com/leaderboardsgg/leaderboard-site/issues/591)
[frontend #592](https://github.com/leaderboardsgg/leaderboard-site/issues/592)

**Comment by TheTedder** [comment]
Is there any situation where we would want to hide someone's role? Is account confirmation status something that should be hidden? I think so, actually. It might be better then to only return this from the `/users/me` endpoint and use a different viewmodel to do so.

**Comment by zysim** [comment]
Come to think of it; I think the role should be returned in /users/me. Though it isn't personally-identifying info, we simply don't need it to be part of the response. You really only need the info in /me

**Comment by zysim** [comment]
But let's keep what we've got

**Comment by TheTedder** [comment]
Closed by #211
