### ISSUE TITLE
Bug: Incorrect Error Responses on Failed Leaderboard Creations

### ISSUE THREAD

**Issue by zysim** [leaderboardsgg/leaderboard-backend#214]
We don't have expected error behaviour for creating Leaderboards.

### Step(s) to Reproduce

1. Create a Leaderboard with an existing name/slug
1. Create a Leaderboard with missing/invalid fields

### Expected Result

1. Existing name/slug should 409
2. Missing/invalids should 422

### Actual Outcome

1. Existing names/slugs 500s
1. Missing/invalids 400s

**Comment by TheTedder** [comment]
>     * Fetching users:
>       
>       * Fetching by ID doesn't work; request param validation outdated

Can you elaborate on this? What exactly is the issue?

**Comment by zysim** [comment]
Can't fetch users by ID because the request validation failed. And it's because the validation is based on an old set of rules.

**Comment by TheTedder** [comment]
It worked for me when I tried it, at least after making the changes in #215.
