### ISSUE TITLE
Task: Test Unicode Support slug names

### ISSUE THREAD

**Issue by Eein** [leaderboardsgg/leaderboard-backend#219]
Depending on desired behavior, slugs should handle Unicode properly 

A package that can handle this is: https://www.nuget.org/packages/Slugify.Core/

Here is a test from the Slugify library with some examples on potential testing requirements:
https://github.com/ctolkien/Slugify/blob/main/tests/Slugify.Core.Tests/SlugHelperTests.cs

### Affected Functionality
When creating slugs for names names, the game may have specific characters that aren't considered in the existing slugging mechanism:

ex: 
-  `Chào thế giới`
- `ライブ・ア・ライブ`

Decide if this should maintain the same, or if it should convert to an ascii representation for compatibility in older devices consuming the api.

### Other Relevant Issues
n/a

**Comment by TheTedder** [comment]
We should have no unicode in URLs. Either we escape all unicode in URLs or just force alphanumeric + dash + underscore. For the two examples given, `/chao-the-gioi` and `/live-a-live` would work fine as slugs imo.

**Comment by TheTedder** [comment]
Personally, I find `/chao-the-gioi` a lot more readable than `/Ch%C3%A0o%20th%E1%BA%BF%20gi%E1%BB%9Bi`.

**Comment by TheTedder** [comment]
Per consensus, we are sticking with no unicode support for now.
