### ISSUE TITLE
Create Leaderboard Endpoint

### ISSUE THREAD

**Issue by TheTedder** [leaderboardsgg/leaderboard-backend#223]
`POST` `/leaderboards/create`.

The request body includes the following fields:
- Name: string
- Slug: string
- Info: string?

The server returns a 401 error if the client is not authenticated.

The server returns a 403 error if the current user's role is not `ADMIN`.

The server returns a 409 error if the provided slug is already in use.

The server returns a 422 error if 
- slug is not between 2 and 80 characters inclusive.
- the slug is not comprised solely of alphanumeric digits, hyphens, and underscores.
- Name is absent or null.
- Slug is absent or null.

Upon succesful leaderboard creation, the server returns 201 CREATED status and a response body that includes the newly-created leaderboard as well as its location on the server.
```[tasklist]
### Tasks
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/214
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/226
```

**Comment by zysim** [comment]
We already have an existing endpoint; `POST /api/leaderboards`. We fix that one, instead.
