### ISSUE TITLE
List Leaderboards Endpoint

### ISSUE THREAD

**Issue by TheTedder** [leaderboardsgg/leaderboard-backend#227]
`GET` `/api/leaderboards`.

This endpoint does not require authentication to access.

The server must return a 200 OK status.

The server must return a JSON response body containing an array of leaderboard objects that have the following fields:
- Id: long
- Name: string
- Slug: string
- Info: string?
- CreatedAt: timestamp
- UpdatedAt: timestamp?
- DeletedAt: timestamp?

Leaderboards that are deleted must not be returned.

**Comment by zysim** [comment]
Endpoint already exists, and it returns the expected fields, plus `Categories`, which of course, is out of scope for now.
