### ISSUE TITLE
Get Leaderboard Endpoint

### ISSUE THREAD

**Issue by TheTedder** [leaderboardsgg/leaderboard-backend#228]
`GET` `/api/leaderboard/{id}`.

This endpoint does not require authentication to access.

If `id` is not a long, the server must return a 404 error.

If the given ID does not correspond to a leaderboard in the database, the server must return a 404 error.

If the given ID corresponds to a leaderboard in the database, the server must return a 200 OK status and a JSON response body containing an object with the following fields:
- Id: long
- Name: string
- Slug: string
- Info: string?
- CreatedAt: timestamp
- UpdatedAt: timestamp?
- DeletedAt: timestamp?

Leaderboards that are deleted may be returned.

**Comment by zysim** [comment]
What about relations? I assume they're returned only with query params passed to them?

**Comment by TheTedder** [comment]
> What about relations? I assume they're returned only with query params passed to them?
> 
> We have the endpoint already and it already has the correct behaviour, with the addition that categories don't get loaded in

We're not doing cats until next sprint so don't worry about it 🙂
