### ISSUE TITLE
Restore Leaderboard Endpoint

### ISSUE THREAD

**Issue by TheTedder** [leaderboardsgg/leaderboard-backend#240]
`PUT` `/leaderboard/{id}/restore` where {id} is a long.

The server must return a 401 error if the client is not authenticated.

The server must return a 403 error if the current user's role is not `ADMIN`.

The server must return a 404 error if the given ID does not correspond to a leaderboard in the database.

The server must return a 404 error if the given ID corresponds to a leaderboard that is not deleted.

The server may use a response body to disambiguate between the two different scenarios that can generate a 404 error.

The server must return a 409 error if the leaderboard cannot be restored because its slug is the same as an existing non-deleted leaderboard.

Upon a successful restoration, the server must set the `DeletedAt` field of the corresponding leaderboard to `null` and return a 204 status code.

**Comment by zysim** [comment]
Actually; shouldn't a non-deleted board cause a 204 instead? Basically communicate a "we didn't have to do anything" instead of a "we couldn't find it".

**Comment by zysim** [comment]
Will implement stuff as mentioned in the issue though, in the meantime.

**Comment by Eein** [comment]
If the endpoint only takes deleted resource ids i think 404 is acceptable here

204 can be misconstrued that something occured
