### ISSUE TITLE
Run Model

### ISSUE THREAD

**Issue by zysim** [leaderboardsgg/leaderboard-backend#39]
Bring the run entity in line with [DB design](https://lucid.app/lucidchart/b2eeb6e7-b1e5-4e10-bfbb-84e968db0fa0/edit?page=0_0&invitationId=inv_8fd08c8f-0f40-43aa-ac55-91eea160ca6d#).
- [ ] Add TimeOrScore field.
- [ ] Add Info field.
- [ ] Rename SubmittedAt field to CreatedAt.
- [ ] Add UpdatedAt field.
- [ ] Add DeletedAt field.

There may be some infrastructure needed so that soft deletes work properly.

**Comment by zysim** [comment]
Why did I close this lmao

**Comment by just-ero** [comment]
Little aside; should this model be renamed to accomodate for score attack leaderboards? Should those still be considered "runs"?

**Comment by zysim** [comment]
Yeah this was discussed some time ago in the Discord. I believe we can still call em runs tho. A playthrough of a game = a run of it. A start and an end and all that.

Unless score attack people call em differently, and have a strong sentiment against calling em runs, I'd say the name can stick.

**Comment by TheTedder** [comment]
We also need to make it so that runs are associated with a User.

**Comment by just-ero** [comment]
Perhaps one or more users?

**Comment by TheTedder** [comment]
> Perhaps one or more users?

That is indeed planned but we're keeping it simple and having one user per run for now.
