### ISSUE TITLE
Add Pronouns Field to User

### ISSUE THREAD

**Issue by zysim** [leaderboardsgg/leaderboard-backend#50]
Forgot to add this lmao. User model lacks a pronoun field right now.

### Affected Functionality

Registrations, updating, and retrieval of users

### Other Relevant Issues

\-

**Comment by zysim** [comment]
Removing this from the MVP as we can simply add pronouns to the username.

**Comment by RageCage64** [comment]
I feel like this is so low effort that we really could include it in the MVP without much trouble. We would have to stick to they/them, she/her, he/him though and iterate if we need more.

**Comment by TheTedder** [comment]
not MVP
