### ISSUE TITLE
MVP: Authentication

### ISSUE THREAD

**Issue by zysim** [leaderboardsgg/leaderboard-backend#51]
We would need an authentication middleware. Refer to ASP.NET's [docs on this](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-6.0). The [Trello board](https://trello.com/b/eDp90mdx) mentioned [KeyCloak](https://www.keycloak.org/), which is something we can look into as well.

**Comment by RageCage64** [comment]
Don't we have this already? What do we need that we don't have already?

**Comment by zysim** [comment]
Oh yeah we do now. I'll close this.
