### ISSUE TITLE
MVP: Allow Mods/Admins to Batch-Create Runs/Leaderboards

### ISSUE THREAD

**Issue by zysim** [leaderboardsgg/leaderboard-backend#56]
We need to allow easy migration of existing data from other sites into ours. I'd imagine that we could, on top of ensuring only mods are able to attempt batch creations, we also set a time limit for this action.

This task shall be split into three parts:
1. The controller actions + endpoints to handle batch creations
2. Business logic to verify the user is a mod or admin
3. A script that calls the controller actions

On top of this, of course, is to build UI for mods and admins. https://github.com/leaderboardsgg/leaderboard-site/issues/208 will handle it.

**Comment by TheTedder** [comment]
not MVP
