### ISSUE TITLE
Task: Create Migration to Update Leaderboard ID Type

### ISSUE THREAD

**Issue by zysim** [leaderboardsgg/leaderboard-backend#64]
`Leaderboard`'s ID was initially set to `long`, and that fact is included in the initial migration files. As its ID type is now `ulong`, we'll need to run a second migration that updates its type.

To run a migration via the `dotnet` CLI:
```bash
$ dotnet tool restore # If you haven't installed CLI tools yet
$ dotnet ef migrations --project LeaderboardBackend add -c ApplicationContext UpdateLeaderboardIdType
```

### Affected Functionality

As long as we don't merge in PRs that create new models yet, _especially_ those that have a relationship with Leaderboards, we should be fine.

### Other Relevant Issues

\-

**Comment by RageCage64** [comment]
Offline discussion lead to this no longer being required. GUIDs are only really important as an identifier for users, not really for anything else.
