### ISSUE TITLE
Discussion: Implement Logging Library

### ISSUE THREAD

**Issue by zysim** [leaderboardsgg/leaderboard-backend#83]
What's a good logging library for ASP.NET? I'm thinking it will be useful to start including it in either near the end of MVP or post.

**Comment by RageCage64** [comment]
The base logger should give us everything we need: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0

**Comment by zysim** [comment]
Oh yeah, this slipped my mind. I'll use that for now.

Tbh I thought this would've been a longer discussion lmao. Will close this if no one else chimes in with anything in a couple days.

**Comment by RageCage64** [comment]
Yeah I'm just wary of adding a logging dependency before proving we have a need for it. If it gets to a point where it would benefit us I'm pretty sure ASP NET Core logging libraries are usually just a fix to `Program.cs` to implement.
